mesd_security_security_homepage:
    pattern:  /services
    defaults: { _controller: MESDSecurityAuthenticationBundle:Default:index }

MESDORMedORMedBundle_consent:
    resource: "@MESDSecurityAuthenticationBundle/Resources/config/routing/security.yml"
    prefix:   /