mesd_security_security_homepage:
    pattern:  /services
    defaults: { _controller: MesdSecurityAuthenticationBundle:Default:index }

mesd_security_security_security:
    resource: "@MesdSecurityAuthenticationBundle/Resources/config/routing/security.yml"
    prefix:   /