# src/MESD/Security/AuthenticationBundle/Resources/config/services.yml
services:
    security.authentication.provider.universal_auth:
        class:  Mesd\Security\AuthenticationBundle\Security\Authentication\UniversalAuthenticationProvider
        arguments: [ '@security.user_checker', '', '' ]
