login:
    path:     /login
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:login }

login_check:
    path:     /auth
    requirements: { _method: POST }

logout:
    path:     /logout

registration:
    path:     /register
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:register }

reset_password:
    path:     /resetpass
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:resetPassword }

does_not_exist:
    path:     /doesnotexist
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:doesNotExist }

verification:
    path:     /verify/{email}/{verification}
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:verify }

change_password:
    path:     /changepass
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:changePassword }

check_email:
    path:     /checkemail
    defaults: { _controller: MesdSecurityAuthenticationBundle:Security:checkEmail }
